import os

a = Analysis(
    ['main.py'],
    pathex=[],
    # The parser is bundled; crimson_rs in the folder is only a shim that
    # forwards to it.
    binaries=[
        ('dmm_parser/dmm_parser.pyd', 'dmm_parser'),
        ('dmm_parser/dmm_parser.abi3.so', 'dmm_parser'),
    ],
    datas=[
        ('parc_parser.dll', '.'),
        ('item_names.json', '.'),
        ('store_names.json', '.'),
        ('item_templates.json', '.'),
        ('master_templates.json', '.'),
        ('item_limits.json', '.'),
        ('item_category_map.json', '.'),
        ('max_enchant_map.json', '.'),
        ('waypoint_templates_community.json', '.'),
        ('abyss_gimmick_templates.json', '.'),
        ('knowledge_keys_all.json', '.'),
        ('community_knowledge_keys.json', '.'),
        ('quest_names.json', '.'),
        ('quest_database.json', '.'),
        ('mission_names.json', '.'),
        ('quest_stage_map.json', '.'),
        ('stage_names.json', '.'),
        ('gimmick_respawn_timers.json', '.'),
        ('quest_chains.json', '.'),
        ('dye_slot_counts.json', '.'),
        ('buff_skill_descriptions.json', '.'),
        ('game_map.json', '.'),
        ('localizationstring_eng_items.tsv', '.'),
        ('locale', 'locale'),
        ('knowledge_packs', 'knowledge_packs'),
        # The other six packs live in the repository root and were never
        # bundled - only the one copy in this folder was. In the EXE six of
        # seven packs were therefore simply absent.
        (os.path.join(SPECPATH, '..', 'knowledge_packs'), 'knowledge_packs'),
        ('dmm_parser', 'dmm_parser'),
        ('crimson_rs', 'crimson_rs'),
        ('table_layout.py', '.'),
    ],
    hiddenimports=[
        'lz4',
        'lz4.block',
        'cryptography',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.primitives.ciphers.algorithms',
        'iteminfo_parser',
        'parc_inserter3',
        'parc_inserter2',
        'parc_serializer',
        'save_parser',
        'save_pet_rename',
        'quest_deep_parser',
        'questinfo_parser',
        'item_template_db',
        'native_backend',
        'app_version',
        'startup_splash',
        'theme_support',
        'ben_save_decrypt',
        # imported inside functions only, hence listed explicitly
        'schema_item_index',
        'save_check',
        'game_version',
        'table_layout',
        'dmm_parser',
        'dmm_parser.enums',
        'dmm_parser.pack_mod',
        'crimson_rs',
        'crimson_rs.enums',
        'crimson_rs.create_pack',
        'crimson_rs.pack_mod',
        'crimson_rs.validate_game_dir',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PyQt5'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CrimsonSaveEditorStandalone',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    icon='app_icon.ico',
    codesign_identity=None,
    entitlements_file=None,
)
