"""Readable names for the equipment buffs (buffinfo keys).

Why this exists: the buff list used to show internal names ("SmithStone DDD",
"PuplePoison") next to descriptions that belonged to SKILLS with the same
number - e.g. "Climb Speed Multiplier - Fortune - increases silver drop
chance". Buff and skill keys are two separate number ranges, so about fifty
of those descriptions described something else entirely.

These names come from the game itself: the internal name of each buff
(buffinfo string_key) and the Korean developer notes stored inside the buff
data (e.g. 공격력 증가 = "attack increase"), translated. Abyss Gear effect
names are kept where the Korean note confirms the gear.

Each entry: key -> (name, group, what it does).
Groups are sorted in GROUP_ORDER; "Debuff" and "Internal" are not useful on
gear (negative, or visual/AI-only) and are marked as such in the list.
"""

GROUP_ORDER = ["Stats", "Regen", "Resist", "Damage", "Movement", "Gathering", "Social",
               "Stealth", "Gear passive", "Combat", "Food/Potion", "Debuff", "Internal"]

GROUP_HINT = {
    "Debuff": "Negative effect - usually not wanted on gear.",
    "Internal": "Visual, AI or boss mechanic - does nothing useful on gear.",
    "Gear passive": "Marker of a specific weapon/armour; its effect depends on that item's skills.",
}

BUFFS = {
    1000000: ("Temperature", "Internal", "body temperature system"),
    1000001: ("Max Health +", "Stats", "more maximum Health"),
    1000002: ("Max Spirit +", "Stats", "more maximum Spirit"),
    1000003: ("Max Stamina +", "Stats", "more maximum Stamina"),
    1000004: ("Attack +", "Stats", "more attack power (Abyss Gear: Destruction)"),
    1000005: ("Defense +", "Stats", "more defense (Abyss Gear: Fortification)"),
    1000006: ("Attack Speed +", "Stats", "faster attacks, level 1-15"),
    1000007: ("Movement Speed +", "Movement", "faster movement, level 1-15"),
    1000008: ("Health Regen", "Regen", "Health per second (Abyss Gear: Vitality)"),
    1000009: ("Spirit Regen", "Regen", "Spirit per second (Abyss Gear: Composure)"),
    1000010: ("Intimidation +", "Stats", "more pressure on enemies"),
    1000011: ("Damage Reduction +", "Stats", "less damage taken"),
    1000012: ("Fire Resistance", "Resist", "less fire damage"),
    1000013: ("Ice Resistance", "Resist", "less ice damage"),
    1000014: ("Lightning Resistance", "Resist", "less lightning damage and shock build-up"),
    1000015: ("Stamina Cost -", "Regen", "changes Stamina use (can raise or lower it)"),
    1000016: ("Max Health %", "Stats", "maximum Health in percent"),
    1000017: ("Ice Shield", "Combat", "ice shield effect"),
    1000018: ("Minimum Health", "Combat", "minimum Health limit"),
    1000019: ("Fire Arrows", "Combat", "arrows deal fire damage"),
    1000020: ("Poison", "Debuff", "poison damage over time"),
    1000021: ("Debuff Resistance", "Resist", "resists negative effects"),
    1000022: ("Purple Poison", "Debuff", "poison damage over time"),
    1000023: ("White Poison", "Debuff", "poison damage over time"),
    1000024: ("NPC Mood State", "Internal", "AI only: joy, sadness, pain, anger, heat, cold"),
    1000025: ("Non-Slip", "Movement", "no slipping on ice"),
    1000026: ("Bleeding", "Debuff", "bleeding damage over time"),
    1000027: ("Red Lightning", "Debuff", "red lightning hazard"),
    1000028: ("Bismuth Poisoning", "Debuff", "bismuth hazard"),
    1000029: ("Boss Weaken", "Internal", "lowers a boss's defense (boss mechanic)"),
    1000030: ("Damage over Time", "Debuff", "Health damage over time, level 1-10"),
    1000031: ("Lava Gas", "Debuff", "coughing, lava gas damage"),
    1000032: ("Abyss Poison", "Debuff", "abyss poison damage"),
    1000033: ("Bee Swarm", "Debuff", "bee swarm damage"),
    1000034: ("Spider Swarm", "Debuff", "spider swarm damage"),
    1000035: ("Rat Swarm", "Debuff", "rat swarm damage"),
    1000036: ("Locust Swarm", "Debuff", "locust swarm damage"),
    1000037: ("Detection Distance", "Stealth", "how far enemies notice you"),
    1000038: ("Super Armor", "Combat", "cannot be staggered, 2 levels"),
    1000039: ("Invincible", "Combat", "no damage taken"),
    1000040: ("Fire Weapon", "Combat", "weapon deals fire damage"),
    1000041: ("Nature's Protection", "Combat", "protection effect"),
    1000042: ("Drunk", "Debuff", "drunk camera effect"),
    1000043: ("Out of Bounds (Desert)", "Internal", "slower attacks outside the play area"),
    1000044: ("Ice Ground Check", "Internal", "detects icy ground"),
    1000045: ("Guard", "Combat", "guard state"),
    1000046: ("Stamina Regen", "Regen", "Stamina per second"),
    1000047: ("Abyss Health", "Stats", "Health bonus from the Abyss"),
    1000048: ("Abyss Spirit", "Stats", "Spirit bonus from the Abyss"),
    1000049: ("Abyss Stamina", "Stats", "Stamina bonus from the Abyss"),
    1000050: ("Max Health + (food)", "Food/Potion", "food effect"),
    1000051: ("Health Drain", "Debuff", "loses Health over time"),
    1000052: ("Spirit Drain", "Debuff", "loses Spirit per second"),
    1000053: ("Stamina Drain", "Debuff", "loses Stamina per second"),
    1000054: ("Machine Overload", "Internal", "machine enemy mechanic"),
    1000055: ("Stamina Cost - (food)", "Food/Potion", "food effect"),
    1000056: ("AI Difficulty", "Internal", "enemy AI setting"),
    1000057: ("Detection by Light", "Stealth", "how much light makes you visible"),
    1000058: ("Nature Spirit Regen", "Regen", "Spirit recovery from nature"),
    1000059: ("Nature Health Regen", "Regen", "Health recovery from nature"),
    1000060: ("Lava", "Debuff", "lava damage"),
    1000061: ("Spider Web", "Debuff", "slower movement and attacks"),
    1000062: ("Drowsiness", "Debuff", "about to fall asleep: slower movement and attacks"),
    1000063: ("Sulphur Gas", "Debuff", "coughing, sulphur damage over time"),
    1000064: ("NPC Injury State", "Internal", "AI only: drunk, leg or arm injury"),
    1000065: ("Spider Web (visual)", "Internal", "visual effect only"),
    1000066: ("Equipment Drop Rate +", "Gathering", "more equipment drops, +1% per level"),
    1000067: ("Lightning", "Debuff", "lightning hazard"),
    1000068: ("Detection Reaction", "Stealth", "how enemies react when they notice you"),
    1000069: ("Disguise (no effect)", "Internal", "description text only, no effect"),
    1000070: ("Blizzard", "Debuff", "blizzard damage, freezing"),
    1000071: ("Ore Drops +", "Gathering", "more ore from mining"),
    1000072: ("Plant Drops +", "Gathering", "more plants from gathering"),
    1000073: ("Animal Drops +", "Gathering", "more materials from animals"),
    1000074: ("Critical Rate +", "Stats", "more critical hits, level 1-15"),
    1000075: ("Out of Bounds (Blizzard)", "Internal", "slower attacks outside the play area"),
    1000076: ("Attack + (potion)", "Food/Potion", "potion effect"),
    1000077: ("Out of Bounds (Water)", "Internal", "slower attacks outside the play area"),
    1000078: ("Combat High", "Stats", "better stats during combat"),
    1000079: ("Out of Bounds", "Internal", "slower attacks outside the play area"),
    1000080: ("Temperature (boss)", "Internal", "boss mechanic"),
    1000081: ("Daze Immunity (boss)", "Internal", "boss mechanic"),
    1000082: ("Accuracy +", "Stats", "better hit chance, level 1-15"),
    1000083: ("Waterfall Slow", "Internal", "slower movement in waterfalls"),
    1000084: ("Block Damage (situation)", "Internal", "scripted damage block"),
    1000085: ("Fire Fist", "Combat", "fire strikes"),
    1000086: ("Battle Order", "Combat", "battle order effect"),
    1000087: ("Civilian Disguise", "Stealth", "passes as a civilian"),
    1000088: ("Darkness King Halberd", "Gear passive", "spinning slash uses extra resource"),
    1000089: ("Food Effect Level +", "Food/Potion", "stronger food effects"),
    1000090: ("Damage vs Machines", "Damage", "more damage against machines"),
    1000091: ("Crafting Material Saving", "Gathering", "chance to save crafting materials"),
    1000092: ("Weaken (Jijeongta)", "Internal", "lowers a boss's defense (boss mechanic)"),
    1000093: ("Log Drops +", "Gathering", "more wood from logging"),
    1000094: ("Attack + (Smith Stone)", "Stats", "attack increase from a smith stone"),
    1000095: ("Temperature Change Slower", "Resist", "heats up and cools down more slowly"),
    1000096: ("Damage Reduction + (socket)", "Stats", "less damage taken"),
    1000097: ("Guard Efficiency + (socket)", "Stats", "better guarding"),
    1000098: ("Weaken, breakable (Jijeongta)", "Internal", "boss mechanic"),
    1000099: ("NPC Trust Gain +", "Social", "gain trust with people faster"),
    1000100: ("Climb Speed + (socket)", "Movement", "faster climbing"),
    1000101: ("Food Poisoning", "Debuff", "bad food"),
    1000102: ("Mounted Hit Counter", "Internal", "counts hits while mounted"),
    1000103: ("Legendary Wolf (visual)", "Internal", "visual effect only"),
    1000104: ("Trap Slow", "Debuff", "slower movement"),
    1000105: ("Logging Axe Equipped", "Gathering", "marks a (best) logging axe as equipped"),
    1000106: ("Fishing Time -", "Gathering", "fish bite faster"),
    1000107: ("Swim Speed + (socket)", "Movement", "faster swimming"),
    1000108: ("Damage vs Earthen Beings", "Damage", "more damage against earthen beings (Hexe)"),
    1000109: ("Damage vs Humanoids", "Damage", "more damage against humans"),
    1000110: ("Damage vs Walkers", "Damage", "more damage against walkers (golems)"),
    1000111: ("Damage vs Mighty Foes", "Damage", "more damage against bosses"),
    1000112: ("Damage vs Beasts", "Damage", "more damage against animals"),
    1000113: ("Damage vs Abyssal Creatures", "Damage", "more damage against abyss creatures"),
    1000114: ("Contribution EXP +", "Social", "more contribution experience"),
    1000115: ("Skill EXP +", "Social", "more skill experience"),
    1000116: ("Arrow Saving", "Combat", "chance not to use up an arrow"),
    1000117: ("Silver Drop Chance +", "Gathering", "more silver from enemies"),
    1000118: ("Ludvig Lightning (visual)", "Internal", "visual effect only"),
    1000119: ("Theft Bonus", "Social", "extra steal chance"),
    1000120: ("Bastier Gear", "Gear passive", "fire enhancement uses extra resource"),
    1000121: ("White Horn Machine Frenzy", "Internal", "boss: faster attacks and movement"),
    1000122: ("Stamina Regen + (socket)", "Regen", "faster natural Stamina recovery"),
    1000123: ("Bonus Crafting Result", "Gathering", "chance of an extra crafted item"),
    1000124: ("Pet Trust Gain +", "Social", "pets trust you faster"),
    1000125: ("Forgotten General", "Gear passive", "gear marker"),
    1000126: ("Disguise: Lonely Jackals", "Stealth", "faction disguise set"),
    1000127: ("Disguise: Drunken Black Bears", "Stealth", "faction disguise set"),
    1000128: ("Disguise: Demeniss", "Stealth", "faction disguise set"),
    1000129: ("Titan Abyss Gear", "Gear passive", "Lightning God's Affliction"),
    1000130: ("Myurdin Sword", "Gear passive", "spinning slash uses extra resource"),
    1000131: ("Split-Horn Sword", "Gear passive", "gear marker"),
    1000132: ("Sizlek Sword", "Gear passive", "lightning enhancement uses extra resource"),
    1000133: ("Master Doo", "Gear passive", "gear marker"),
    1000134: ("Crowman Sword", "Gear passive", "forward slash uses extra resource"),
    1000135: ("Caliburn Rapier", "Gear passive", "gear marker"),
    1000136: ("Reed Devil Sword", "Gear passive", "gear marker"),
    1000137: ("Golden Knight Abyss Gear (Merrick)", "Gear passive", "Order from Above"),
    1000138: ("Hamond Bindel Longsword", "Gear passive", "spinning cut uses extra resource"),
    1000139: ("Red Sentinel Bow", "Gear passive", "gear marker"),
    1000140: ("Ludvig Sword", "Gear passive", "lightning enhancement uses extra resource"),
    1000141: ("Stamina Recovery Change", "Regen", "raises or lowers natural Stamina recovery"),
    1000142: ("Antumbra Two-Hand Sword", "Gear passive", "spinning slash uses extra resource"),
    1000143: ("Temperature (wagon)", "Internal", "wagon temperature"),
    1000144: ("Ator Sword", "Gear passive", "forward slash uses extra resource"),
    1000145: ("Cold", "Debuff", "too cold"),
    1000146: ("Heat", "Debuff", "too hot"),
    1000147: ("Crit vs Plate Armor", "Damage", "more critical hits on plate-armoured enemies"),
    1000148: ("Shackle of Might (Soul Knight Sword)", "Gear passive", "gear marker"),
    1000149: ("Abyss Toxin Immunity", "Resist", "immune to abyss grass toxin"),
    1000150: ("Poison Immunity", "Resist", "immune to hyena poison"),
    1000151: ("Bismuth Immunity", "Resist", "immune to bismuth"),
    1000152: ("Deer King Helm", "Gear passive", "more spinning-slash damage"),
    1000153: ("Resources on Kill", "Combat", "restores resources when you kill"),
    1000154: ("Crit vs Leather Armor", "Damage", "more critical hits on leather-armoured enemies"),
    1000155: ("Queen Spider", "Internal", "boss mechanic"),
    1000156: ("Flame Knight Sword (Tristan)", "Gear passive", "fire enhancement uses extra resource"),
    1000157: ("Crit vs Cloth Armor", "Damage", "more critical hits on cloth-armoured enemies"),
    1000158: ("Temperature (insects)", "Internal", "insect temperature"),
    1000159: ("Moonhead Giant Spear (fire)", "Gear passive", "crescent-moon form"),
    1000160: ("Lanford Abyss Gear", "Gear passive", "Parting Gift"),
    1000161: ("White Horn Gear", "Gear passive", "ice enhancement uses extra resource"),
    1000162: ("Goyen Sword", "Gear passive", "spinning slash uses extra resource"),
    1000163: ("Moonhead Giant Spear (ice)", "Gear passive", "half-moon form"),
    1000164: ("Moonhead Giant Spear (lightning)", "Gear passive", "full-moon form"),
    1000165: ("Disguise: Desert Harriers", "Stealth", "faction disguise set"),
    1000166: ("Player Sense", "Internal", "enemy perception check"),
    1000167: ("Health to Spirit", "Combat", "loses Health, gains Spirit over time"),
    1000168: ("Umbra Wing Hold", "Internal", "boss mechanic"),
    1000169: ("Antumbra Warhammer Abyss Gear", "Gear passive", "spinning cut uses extra resource"),
    1000170: ("Solid Bringer Warhammer", "Gear passive", "gear marker"),
    1000171: ("Block Learning", "Internal", "blocks learning from the intro"),
    1000172: ("Plate Armor Mastery", "Stats", "bonus for wearing plate armour"),
    1000173: ("Leather Armor Mastery", "Stats", "bonus for wearing leather armour"),
    1000174: ("Cloth Armor Mastery", "Stats", "bonus for wearing cloth armour"),
    1000175: ("Karanda Abyss Gear", "Gear passive", "Pillar of Wind - wind enhancement"),
    1000176: ("Pickaxe Equipped", "Gathering", "marks a (best) pickaxe as equipped"),
    1000177: ("Spirit Cost - (food)", "Food/Potion", "food effect"),
    1000178: ("Health Regen (food)", "Food/Potion", "food effect"),
    1000179: ("Spirit Regen (food)", "Food/Potion", "food effect"),
    1000180: ("Attack + (food)", "Food/Potion", "food effect"),
    1000181: ("Defense + (food)", "Food/Potion", "food effect"),
    1000182: ("Fire Resistance (food)", "Food/Potion", "food effect"),
    1000183: ("Ice Resistance (food)", "Food/Potion", "food effect"),
    1000184: ("Lightning Resistance (food)", "Food/Potion", "food effect"),
    1000185: ("Fall Damage - (food)", "Food/Potion", "food effect"),
    1000186: ("Attack Speed + (food)", "Food/Potion", "food effect"),
    1000187: ("Plate Mastery: Damage Reduction", "Stats", "less damage taken in plate armour"),
    1000188: ("Leather Mastery: Bonus", "Stats", "bonus in leather armour"),
    1000189: ("Spirit Cost -", "Regen", "changes Spirit use (can raise or lower it)"),
    1000190: ("Fall Damage -", "Resist", "less fall damage"),
    1000191: ("Sleep Immunity", "Resist", "food cannot put you to sleep"),
    1000192: ("Daze Immunity (food)", "Resist", "no daze"),
    1000193: ("Awakened Ludvig (visual)", "Internal", "visual effect only"),
    1000194: ("Blood Splatter (visual)", "Internal", "visual effect only"),
    1000195: ("Fishing Auto-Reel", "Gathering", "reels in automatically"),
    1000196: ("Disguise: Dawn Moon", "Stealth", "faction disguise set"),
    1000197: ("Disguise: Faceless", "Stealth", "faction disguise set"),
    1000198: ("Disguise: Dusksong Thieves", "Stealth", "faction disguise set"),
    1000199: ("Disguise: Pirates", "Stealth", "faction disguise set"),
    1000200: ("Wolf Disguise", "Stealth", "wild wolves ignore you"),
    1000201: ("Bear Disguise", "Stealth", "wild bears ignore you"),
    1000202: ("Deer Disguise", "Stealth", "deer do not flee"),
    1000203: ("Wildlife Disguise", "Stealth", "wild animals ignore you"),
    1000204: ("Defense + (potion)", "Food/Potion", "potion effect"),
    1000205: ("Max Health + (potion)", "Food/Potion", "potion effect"),
    1000206: ("Cloth Mastery: Bonus", "Stats", "bonus in cloth armour"),
    1000207: ("Circus Boss Weak Point", "Internal", "boss mechanic"),
    1000208: ("Health on Attack", "Regen", "restores Health when you hit"),
    1000209: ("Spirit on Attack", "Regen", "restores Spirit when you hit"),
    1000210: ("Stamina on Attack", "Regen", "restores Stamina when you hit"),
    1000211: ("Sell Price +", "Social", "better prices at trade shops"),
    1000212: ("Combo Damage +", "Damage", "more damage in combos"),
    1000213: ("Horseshoes: Stamina Regen", "Regen", "horse gear: faster Stamina recovery"),
    1000214: ("Stirrups: Health Regen", "Regen", "horse gear: faster Health recovery"),
    1000215: ("Disguise: Wyvern Tamers", "Stealth", "faction disguise set"),
    1000216: ("Disguise: Mist Owls", "Stealth", "faction disguise set"),
    1000217: ("Reed Devil Eye Glow (visual)", "Internal", "visual effect only"),
    1000218: ("Myurdin Eye Glow (visual)", "Internal", "visual effect only"),
    1000219: ("Attack + (alchemy)", "Food/Potion", "alchemy effect"),
    1000220: ("Defense + (alchemy)", "Food/Potion", "alchemy effect"),
    1000221: ("Max Health + (alchemy)", "Food/Potion", "alchemy effect"),
    1000222: ("Abyss Kutum (visual)", "Internal", "visual effect only"),
    1000223: ("Health when Hit", "Regen", "restores Health when you are hit"),
    1000224: ("Spirit when Hit", "Regen", "restores Spirit when you are hit"),
    1000225: ("Crowd-Control Immunity", "Resist", "cannot be knocked down or stunned"),
    1000226: ("Machine Drops +", "Gathering", "more parts from machines"),
    1000227: ("Disguise: Thorel Demeniss", "Stealth", "faction disguise set"),
    1000228: ("Disguise: Bleed Blades", "Stealth", "faction disguise set"),
    1000229: ("Disguise: Bandits", "Stealth", "faction disguise set"),
    1000230: ("Disguise: Antumbra", "Stealth", "faction disguise set"),
    1000231: ("Disguise: Deer King Saigord", "Stealth", "faction disguise set"),
    1000232: ("Disguise: Dewhaven", "Stealth", "faction disguise set"),
    1000233: ("Disguise: Steel Arrows", "Stealth", "faction disguise set"),
    1000234: ("Disguise: Wolf Pursuers", "Stealth", "faction disguise set"),
    1000235: ("Boss Eye Glow (visual)", "Internal", "visual effect only"),
    1000236: ("White Horn Eye Glow (visual)", "Internal", "visual effect only"),
    1000237: ("Nuclear Fusion (visual)", "Internal", "visual effect only"),
    1000238: ("Reed Devil Afterimage (visual)", "Internal", "visual effect only"),
    1000239: ("Reed Devil Clone Afterimage (visual)", "Internal", "visual effect only"),
    1000240: ("Hexe Marie (visual)", "Internal", "visual effect only"),
    1000241: ("Wizard Bracelet (visual)", "Internal", "visual effect only"),
    1000242: ("Wizard Halo (visual)", "Internal", "visual effect only"),
    1000243: ("Giant Titan (visual)", "Internal", "visual effect only"),
    1000244: ("Boss Electricity", "Internal", "boss mechanic"),
    1000245: ("Disguise: Halsius", "Stealth", "faction disguise set"),
    1000246: ("Lava Myurdin (visual)", "Internal", "visual effect only"),
    1000247: ("Oongka Roar (visual)", "Internal", "visual effect only"),
    1000248: ("Stamina when Hit", "Regen", "restores Stamina when you are hit"),
    1000249: ("Non-Slip Check", "Internal", "checks for non-slip"),
    1000250: ("Ogre Abyss Gear", "Gear passive", "Colossal Might"),
    1000251: ("Silver Armor", "Gear passive", "gear marker"),
    1000252: ("Health on Attack +", "Regen", "restores Health when you hit"),
    1000253: ("Hexe Marie Gear", "Gear passive", "gear marker"),
    1000254: ("Tarandus Warrior Gear", "Gear passive", "gear marker"),
    1000255: ("Skevald Abyss Gear", "Gear passive", "Putrid Touch"),
    1000256: ("Trukan Gear", "Gear passive", "gear marker"),
    1000257: ("Leebur Abyss Gear", "Gear passive", "Shadow Claw - forward slash uses extra resource"),
    1000258: ("Priscus Abyss Gear", "Gear passive", "Ancient Retribution"),
    1000259: ("Catfish Abyss Gear", "Gear passive", "Rising Torrent"),
    1000260: ("Kearus Abyss Gear", "Gear passive", "Howling of Chaos"),
    1000261: ("Praevus Abyss Gear", "Gear passive", "Ancient Wrath"),
    1000262: ("Spirit on Attack +", "Regen", "restores Spirit when you hit"),
    1000263: ("Muscan Abyss Gear", "Gear passive", "The Showstopper"),
    1000264: ("Gwen Kraber's Spear", "Gear passive", "ice enhancement uses extra resource"),
    1000265: ("Antumbra Spear Abyss Gear", "Gear passive", "gear marker"),
    1000266: ("Primus Abyss Gear", "Gear passive", "Ancient Reckoning - wind enhancement"),
    1000267: ("Boss Pause Counter", "Internal", "boss mechanic"),
    1000268: ("Boss Threat Counter", "Internal", "boss mechanic"),
    1000269: ("Bump Counter", "Internal", "counts collisions"),
    1000270: ("Health to Spirit (text only)", "Internal", "description text only"),
    1000271: ("Electric Shock (visual)", "Internal", "visual effect only"),
    1000272: ("Wet", "Debuff", "wet status"),
    1000273: ("Stamina on Attack +", "Regen", "restores Stamina when you hit"),
    1000274: ("Golden Star Overload", "Combat", "faster attacks and movement, with effect"),
    1000275: ("Disguise: Flame Knights", "Stealth", "faction disguise set"),
    1000276: ("Difficulty", "Internal", "difficulty setting"),
    1000277: ("Difficulty (boss)", "Internal", "difficulty setting"),
    1000278: ("Difficulty (player)", "Internal", "easy mode: damage taken / attack"),
    1000279: ("Wild Spirit Boar Stacks", "Internal", "logging event mechanic"),
    1000280: ("Fire Resistance (gear)", "Resist", "less fire damage"),
    1000281: ("Ice Resistance (gear)", "Resist", "less ice damage"),
    1000282: ("Lightning Resistance (gear)", "Resist", "less lightning damage"),
}
